name: time_capsule
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.4+2

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  ntp: ^2.0.0
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  path: any
  file_picker: any
  uuid: any
  cryptography: any
  open_filex: ^4.7.0
  share_plus: ^10.0.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true
